In [1]:
import pandas as pd
import numpy as np
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler as mms
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error,confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor 
from sklearn.datasets import make_classification
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier,RandomForestClassifier
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor,RandomForestRegressor
from sklearn.decomposition import PCA

In [2]:
train=pd.read_csv('C:/Users/sudarson.SUDARSON/Downloads/Train.csv')
test=pd.read_csv('C:/Users/sudarson.SUDARSON/Downloads/Test.csv')

In [3]:
train.shape

(8523, 12)

In [4]:
test.shape

(5681, 11)

In [5]:
train.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

<h1>droping null rows<h1>

In [44]:
#test=test.dropna()
#test.isnull().sum()
#train=train.dropna()
#train.isnull().sum()

In [6]:
trainy=train.Item_Outlet_Sales
trainy.shape

(8523,)

In [7]:
trainx=train.iloc[0:,0:11]
trainx.shape

(8523, 11)

In [8]:
test.shape

(5681, 11)

In [9]:
d=trainx.append(test,sort=False,ignore_index=True)

In [10]:
d.shape

(14204, 11)

In [11]:
d.Item_Identifier.unique()

array(['FDA15', 'DRC01', 'FDN15', ..., 'NCF55', 'NCW30', 'NCW05'],
      dtype=object)

In [12]:
d.Item_Weight.fillna(d.Item_Weight.mean(),inplace=True)
d.Outlet_Size.fillna("others",inplace=True)

In [13]:
d.Outlet_Location_Type.unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [14]:
d.Item_Fat_Content=train.Item_Fat_Content.replace("LF","Low Fat").replace("low fat","Low Fat").replace("reg","Regular")

In [15]:
d.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
14199    False
14200    False
14201    False
14202    False
14203    False
Length: 14204, dtype: bool

In [16]:
d.Item_Visibility.describe()

count    14204.000000
mean         0.065953
std          0.051459
min          0.000000
25%          0.027036
50%          0.054021
75%          0.094037
max          0.328391
Name: Item_Visibility, dtype: float64

In [17]:
dummy=pd.get_dummies(d)
dummy=pd.get_dummies(dummy,columns=["Outlet_Establishment_Year"])

In [18]:
dummy

Item_Weight  Item_Visibility  Item_MRP  Item_Identifier_DRA12  \
0             9.30         0.016047  249.8092                      0   
1             5.92         0.019278   48.2692                      0   
2            17.50         0.016760  141.6180                      0   
3            19.20         0.000000  182.0950                      0   
4             8.93         0.000000   53.8614                      0   
...            ...              ...       ...                    ...   
14199        10.50         0.013496  141.3154                      0   
14200         7.60         0.142991  169.1448                      0   
14201        10.00         0.073529  118.7440                      0   
14202        15.30         0.000000  214.6218                      0   
14203         9.50         0.104720   79.7960                      0   

       Item_Identifier_DRA24  Item_Identifier_DRA59  Item_Identifier_DRB01  \
0                          0                      0                      0   
1                          0                      0                      0   
2                          0                      0                      0   
3                          0                      0                      0   
4                          0                      0                      0   
...                      ...                    ...                    ...   
14199                      0                      0                      0   
14200                      0                      0                      0   
14201                      0                      0                      0   
14202                      0                      0                      0   
14203                      0                      0                      0   

       Item_Identifier_DRB13  Item_Identifier_DRB24  Item_Identifier_DRB25  \
0                          0                      0                      0   
1                          0                      0                      0   
2                          0                      0                      0   
3                          0                      0                      0   
4                          0                      0                      0   
...                      ...                    ...                    ...   
14199                      0                      0                      0   
14200                      0                      0                      0   
14201                      0                      0                      0   
14202                      0                      0                      0   
14203                      0                      0                      0   

       ...  Outlet_Type_Supermarket Type3  Outlet_Establishment_Year_1985  \
0      ...                              0                               0   
1      ...                              0                               0   
2      ...                              0                               0   
3      ...                              0                               0   
4      ...                              0                               0   
...    ...                            ...                             ...   
14199  ...                              0                               0   
14200  ...                              0                               0   
14201  ...                              0                               0   
14202  ...                              0                               0   
14203  ...                              0                               0   

       Outlet_Establishment_Year_1987  Outlet_Establishment_Year_1997  \
0                                   0                               0   
1                                   0                               0   
2                                   0                               0   
3                                   0              

In [19]:
dummy.corr()

Item_Weight  Item_Visibility  Item_MRP  \
Item_Weight                        1.000000        -0.013641  0.033002   
Item_Visibility                   -0.013641         1.000000 -0.006351   
Item_MRP                           0.033002        -0.006351  1.000000   
Item_Identifier_DRA12             -0.006306        -0.015177  0.000275   
Item_Identifier_DRA24              0.032885        -0.010475  0.009838   
...                                     ...              ...       ...   
Outlet_Establishment_Year_1999     0.000839        -0.047289  0.000892   
Outlet_Establishment_Year_2002     0.000350        -0.034292 -0.000832   
Outlet_Establishment_Year_2004     0.000960        -0.034870  0.000576   
Outlet_Establishment_Year_2007    -0.000888        -0.032637 -0.000034   
Outlet_Establishment_Year_2009     0.000890        -0.040590 -0.000023   

                                Item_Identifier_DRA12  Item_Identifier_DRA24  \
Item_Weight                                 -0.006306               0.032885   
Item_Visibility                             -0.015177              -0.010475   
Item_MRP                                     0.000275               0.009838   
Item_Identifier_DRA12                        1.000000              -0.000668   
Item_Identifier_DRA24                       -0.000668               1.000000   
...                                               ...                    ...   
Outlet_Establishment_Year_1999               0.000160              -0.000777   
Outlet_Establishment_Year_2002               0.000172              -0.000765   
Outlet_Establishment_Year_2004               0.000160              -0.000777   
Outlet_Establishment_Year_2007               0.000201              -0.000736   
Outlet_Establishment_Year_2009               0.000183              -0.000754   

                                Item_Identifier_DRA59  Item_Identifier_DRB01  \
Item_Weight                                 -0.022683              -0.022719   
Item_Visibility                              0.034783               0.006359   
Item_MRP                                     0.018801               0.018692   
Item_Identifier_DRA12                       -0.000668              -0.000598   
Item_Identifier_DRA24                       -0.000705              -0.000630   
...                                               ...                    ...   
Outlet_Establishment_Year_1999              -0.000777               0.001209   
Outlet_Establishment_Year_2002              -0.000765              -0.008302   
Outlet_Establishment_Year_2004              -0.000777               0.001209   
Outlet_Establishment_Year_2007              -0.000736               0.001249   
Outlet_Establishment_Year_2009              -0.000754               0.001232   

                                Item_Identifier_DRB13  Item_Identifier_DRB24  \
Item_Weight                                 -0.035300              -0.019662   
Item_Visibility                             -0.028947              -0.020925   
Item_MRP                                     0.019789               0.005070   
Item_Identifier_DRA12                       -0.000634              -0.000598   
Item_Identifier_DRA24                       -0.000668              -0.000630   
...                                               ...                    ...   
Outlet_Establishment_Year_1999               0.000160               0.001209   
Outlet_Establishment_Year_2002               0.000172               0.001220   
Outlet_Establishment_Year_2004               0.000160               0.001209   
Outlet_Establishment_Year_2007               0.000201               0.001249   
Outlet_Establishment_Year_2009               0.000183               0.001232   

                                Item_Identifier_DRB25  ...  \
Item_Weight                                 -0.002472  ...   
Item_Visibility                              0.006940  ...   
Item_MRP                                    -0.014498  ...   
Item_Identif

In [20]:
scaler=mms()

In [21]:
model=scaler.fit(dummy)

In [22]:
scaled=model.transform(dummy)

In [23]:
scaled

array([[0.28252456, 0.04886645, 0.92750715, ..., 0.        , 0.        ,
        0.        ],
       [0.08127419, 0.05870508, 0.0720684 , ..., 0.        , 0.        ,
        1.        ],
       [0.77076511, 0.05103696, 0.46828841, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.32420363, 0.22390557, 0.37119946, ..., 0.        , 0.        ,
        0.        ],
       [0.63977374, 0.        , 0.77815384, ..., 0.        , 1.        ,
        0.        ],
       [0.29443287, 0.31888866, 0.20588425, ..., 0.        , 0.        ,
        0.        ]])

In [24]:
df=pd.DataFrame(scaled)

In [25]:
dfx=df.iloc[0:8523,0:]

In [26]:
trainx,testx=train_test_split(dfx,test_size=0.2)
trainy,testy=train_test_split(trainy,test_size = 0.2)

In [27]:
trainx.shape

(6818, 1610)

In [28]:
testx.shape

(1705, 1610)

In [30]:
trainy.shape

(6818,)

<h1>LINEAR REGRESSION<h1>

In [31]:
reg = LinearRegression().fit(trainx,trainy)
reg.predict(testx)

array([3752., 3528., 2248., ...,  872., 3680., 1208.])

<h1> Decision Tree Regressor<h1>

In [39]:
reg1 = DecisionTreeRegressor(random_state=0).fit(trainx,trainy)

In [40]:
reg1.predict(testx)

array([2407.5328, 2364.9216, 1118.544 , ..., 1677.816 , 5890.9984,
       1789.6704])

<h1>Random Forest Regressor<h1>

In [33]:
reg3 = RandomForestRegressor(max_depth=2, random_state=0).fit(trainx,trainy)
reg3.predict(testx)

array([2162.35178966, 2162.35178966, 2162.35178966, ..., 2162.35178966,
       2162.35178966, 2162.35178966])

<h1>Ada Boost Regressor<h1>

In [34]:
regr = AdaBoostRegressor(random_state=0, n_estimators=100).fit(trainx,trainy)

In [35]:
regr.predict(testx)

array([3606.28790612, 3606.28790612, 3225.78682772, ..., 3606.28790612,
       3606.28790612, 3606.28790612])

<h1>Gradient Boosting Regressor<h1>

In [36]:
clf = GradientBoostingRegressor(random_state=0).fit(trainx,trainy)
clf.predict(testx)

array([2131.04700403, 2139.77052241, 2139.77052241, ..., 2184.925484  ,
       2545.0747478 , 2131.04700403])

In [43]:
print("LinearRegression          = ",reg.score(trainx,trainy))
print("Decision Tree Regressor   = ",reg1.score(trainx,trainy))
print("RandomForestRegressor     = ",reg3.score(trainx,trainy))
print("AdaBoostRegressor         = ",regr.score(trainx,trainy))
print("GradientBoostingRegressor = ",clf.score(trainx,trainy))

LinearRegression          =  0.23282862184816278
Decision Tree Regressor   =  1.0
RandomForestRegressor     =  0.011138436792846207
AdaBoostRegressor         =  -0.5959938065611585
GradientBoostingRegressor =  0.0815073934232301
