In [1]:
import pandas as pd
import numpy as np
from math import sqrt
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler as mms
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error,confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor 
from sklearn.datasets import make_classification
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier,RandomForestClassifier
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor,RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

In [2]:
data=pd.read_csv(r"C:\Users\sudarson.SUDARSON\Desktop\Imarticus\6 Logistic\VaccineUsagePrediction\Vaccine Usage Prediction\Dataset\h1n1_vaccine_prediction.csv")
data

unique_id  h1n1_worry  h1n1_awareness  antiviral_medication  \
0              0         1.0             0.0                   0.0   
1              1         3.0             2.0                   0.0   
2              2         1.0             1.0                   0.0   
3              3         1.0             1.0                   0.0   
4              4         2.0             1.0                   0.0   
...          ...         ...             ...                   ...   
26702      26702         2.0             0.0                   0.0   
26703      26703         1.0             2.0                   0.0   
26704      26704         2.0             2.0                   0.0   
26705      26705         1.0             1.0                   0.0   
26706      26706         0.0             0.0                   0.0   

       contact_avoidance  bought_face_mask  wash_hands_frequently  \
0                    0.0               0.0                    0.0   
1                    1.0               0.0                    1.0   
2                    1.0               0.0                    0.0   
3                    1.0               0.0                    1.0   
4                    1.0               0.0                    1.0   
...                  ...               ...                    ...   
26702                1.0               0.0                    0.0   
26703                1.0               0.0                    1.0   
26704                1.0               1.0                    1.0   
26705                0.0               0.0                    0.0   
26706                1.0               0.0                    0.0   

       avoid_large_gatherings  reduced_outside_home_cont  avoid_touch_face  \
0                         0.0                        1.0               1.0   
1                         0.0                        1.0               1.0   
2                         0.0                        0.0               0.0   
3                         1.0                        0.0               0.0   
4                         1.0                        0.0               1.0   
...                       ...                        ...               ...   
26702                     0.0                        1.0               0.0   
26703                     0.0                        0.0               0.0   
26704                     1.0                        0.0               1.0   
26705                     0.0                        0.0               NaN   
26706                     0.0                        0.0               0.0   

       ...      race     sex               income_level  marital_status  \
0      ...     White  Female              Below Poverty     Not Married   
1      ...     White    Male              Below Poverty     Not Married   
2      ...     White    Male  <= $75,000, Above Poverty     Not Married   
3      ...     White  Female              Below Poverty     Not Married   
4      ...     White  Female  <= $75,000, Above Poverty         Married   
...    ...       ...     ...                        ...             ...   
26702  ...     White  Female  <= $75,000, Above Poverty     Not Married   
26703  ...     White    Male  <= $75,000, Above Poverty     Not Married   
26704  ...     White  Female                        NaN     Not Married   
26705  ...  Hispanic  Female  <= $75,000, Above Poverty         Married   
26706  ...     White    Male  <= $75,000, Above Poverty         Married   

       housing_status          employment                census_msa  \
0                 Own  Not in Labor Force                   Non-MSA   
1                Rent            Employed  MSA, Not Principle  City   
2                 Own            Employed  MSA, Not Principle  City   
3                Rent  Not in Labor Force       MSA, Principle City   
4                 Own            Employed  MSA, Not Principle  City   
...               ...                 ...                       ...   
26

In [3]:
data.isnull().sum()

unique_id                        0
h1n1_worry                      92
h1n1_awareness                 116
antiviral_medication            71
contact_avoidance              208
bought_face_mask                19
wash_hands_frequently           42
avoid_large_gatherings          87
reduced_outside_home_cont       82
avoid_touch_face               128
dr_recc_h1n1_vacc             2160
dr_recc_seasonal_vacc         2160
chronic_medic_condition        971
cont_child_undr_6_mnths        820
is_health_worker               804
has_health_insur             12274
is_h1n1_vacc_effective         391
is_h1n1_risky                  388
sick_from_h1n1_vacc            395
is_seas_vacc_effective         462
is_seas_risky                  514
sick_from_seas_vacc            537
age_bracket                      0
qualification                 1407
race                             0
sex                              0
income_level                  4423
marital_status                1408
housing_status      

In [4]:
data=data.drop("has_health_insur",axis=1)

In [5]:
col=data.columns
null=[]
col

Index(['unique_id', 'h1n1_worry', 'h1n1_awareness', 'antiviral_medication',
       'contact_avoidance', 'bought_face_mask', 'wash_hands_frequently',
       'avoid_large_gatherings', 'reduced_outside_home_cont',
       'avoid_touch_face', 'dr_recc_h1n1_vacc', 'dr_recc_seasonal_vacc',
       'chronic_medic_condition', 'cont_child_undr_6_mnths',
       'is_health_worker', 'is_h1n1_vacc_effective', 'is_h1n1_risky',
       'sick_from_h1n1_vacc', 'is_seas_vacc_effective', 'is_seas_risky',
       'sick_from_seas_vacc', 'age_bracket', 'qualification', 'race', 'sex',
       'income_level', 'marital_status', 'housing_status', 'employment',
       'census_msa', 'no_of_adults', 'no_of_children', 'h1n1_vaccine'],
      dtype='object')

In [6]:
for i in col:
    if data[i].isnull().sum() != 0:
        null.append(i)
        print(i,data[i].isnull().sum())

h1n1_worry 92
h1n1_awareness 116
antiviral_medication 71
contact_avoidance 208
bought_face_mask 19
wash_hands_frequently 42
avoid_large_gatherings 87
reduced_outside_home_cont 82
avoid_touch_face 128
dr_recc_h1n1_vacc 2160
dr_recc_seasonal_vacc 2160
chronic_medic_condition 971
cont_child_undr_6_mnths 820
is_health_worker 804
is_h1n1_vacc_effective 391
is_h1n1_risky 388
sick_from_h1n1_vacc 395
is_seas_vacc_effective 462
is_seas_risky 514
sick_from_seas_vacc 537
qualification 1407
income_level 4423
marital_status 1408
housing_status 2042
employment 1463
no_of_adults 249
no_of_children 249


In [7]:
for i in null:
    print("display('",i,"')"," ,display(data.",i,".unique())")

display(' h1n1_worry ')  ,display(data. h1n1_worry .unique())
display(' h1n1_awareness ')  ,display(data. h1n1_awareness .unique())
display(' antiviral_medication ')  ,display(data. antiviral_medication .unique())
display(' contact_avoidance ')  ,display(data. contact_avoidance .unique())
display(' bought_face_mask ')  ,display(data. bought_face_mask .unique())
display(' wash_hands_frequently ')  ,display(data. wash_hands_frequently .unique())
display(' avoid_large_gatherings ')  ,display(data. avoid_large_gatherings .unique())
display(' reduced_outside_home_cont ')  ,display(data. reduced_outside_home_cont .unique())
display(' avoid_touch_face ')  ,display(data. avoid_touch_face .unique())
display(' dr_recc_h1n1_vacc ')  ,display(data. dr_recc_h1n1_vacc .unique())
display(' dr_recc_seasonal_vacc ')  ,display(data. dr_recc_seasonal_vacc .unique())
display(' chronic_medic_condition ')  ,display(data. chronic_medic_condition .unique())
display(' cont_child_undr_6_mnths ')  ,display(data.

In [8]:
display(' h1n1_worry ')  ,display(data. h1n1_worry .unique())
display(' h1n1_awareness ')  ,display(data. h1n1_awareness .unique())
display(' antiviral_medication ')  ,display(data. antiviral_medication .unique())
display(' contact_avoidance ')  ,display(data. contact_avoidance .unique())
display(' bought_face_mask ')  ,display(data. bought_face_mask .unique())
display(' wash_hands_frequently ')  ,display(data. wash_hands_frequently .unique())
display(' avoid_large_gatherings ')  ,display(data. avoid_large_gatherings .unique())
display(' reduced_outside_home_cont ')  ,display(data. reduced_outside_home_cont .unique())
display(' avoid_touch_face ')  ,display(data. avoid_touch_face .unique())
display(' dr_recc_h1n1_vacc ')  ,display(data. dr_recc_h1n1_vacc .unique())
display(' dr_recc_seasonal_vacc ')  ,display(data. dr_recc_seasonal_vacc .unique())
display(' chronic_medic_condition ')  ,display(data. chronic_medic_condition .unique())
display(' cont_child_undr_6_mnths ')  ,display(data. cont_child_undr_6_mnths .unique())
display(' is_health_worker ')  ,display(data. is_health_worker .unique())
display(' is_h1n1_vacc_effective ')  ,display(data. is_h1n1_vacc_effective .unique())
display(' is_h1n1_risky ')  ,display(data. is_h1n1_risky .unique())
display(' sick_from_h1n1_vacc ')  ,display(data. sick_from_h1n1_vacc .unique())
display(' is_seas_vacc_effective ')  ,display(data. is_seas_vacc_effective .unique())
display(' is_seas_risky ')  ,display(data. is_seas_risky .unique())
display(' sick_from_seas_vacc ')  ,display(data. sick_from_seas_vacc .unique())
display(' qualification ')  ,display(data. qualification .unique())
display(' income_level ')  ,display(data. income_level .unique())
display(' marital_status ')  ,display(data. marital_status .unique())
display(' housing_status ')  ,display(data. housing_status .unique())
display(' employment ')  ,display(data. employment .unique())
display(' no_of_adults ')  ,display(data. no_of_adults .unique())
display(' no_of_children ')  ,display(data. no_of_children .unique())

' h1n1_worry '

array([ 1.,  3.,  2.,  0., nan])

' h1n1_awareness '

array([ 0.,  2.,  1., nan])

' antiviral_medication '

array([ 0.,  1., nan])

' contact_avoidance '

array([ 0.,  1., nan])

' bought_face_mask '

array([ 0.,  1., nan])

' wash_hands_frequently '

array([ 0.,  1., nan])

' avoid_large_gatherings '

array([ 0.,  1., nan])

' reduced_outside_home_cont '

array([ 1.,  0., nan])

' avoid_touch_face '

array([ 1.,  0., nan])

' dr_recc_h1n1_vacc '

array([ 0., nan,  1.])

' dr_recc_seasonal_vacc '

array([ 0., nan,  1.])

' chronic_medic_condition '

array([ 0.,  1., nan])

' cont_child_undr_6_mnths '

array([ 0.,  1., nan])

' is_health_worker '

array([ 0.,  1., nan])

' is_h1n1_vacc_effective '

array([ 3.,  5.,  4.,  2.,  1., nan])

' is_h1n1_risky '

array([ 1.,  4.,  3.,  2.,  5., nan])

' sick_from_h1n1_vacc '

array([ 2.,  4.,  1.,  5.,  3., nan])

' is_seas_vacc_effective '

array([ 2.,  4.,  5.,  3.,  1., nan])

' is_seas_risky '

array([ 1.,  2.,  4.,  3.,  5., nan])

' sick_from_seas_vacc '

array([ 2.,  4.,  1.,  5., nan,  3.])

' qualification '

array(['< 12 Years', '12 Years', 'College Graduate', 'Some College', nan],
      dtype=object)

' income_level '

array(['Below Poverty', '<= $75,000, Above Poverty', '> $75,000', nan],
      dtype=object)

' marital_status '

array(['Not Married', 'Married', nan], dtype=object)

' housing_status '

array(['Own', 'Rent', nan], dtype=object)

' employment '

array(['Not in Labor Force', 'Employed', 'Unemployed', nan], dtype=object)

' no_of_adults '

array([ 0.,  2.,  1.,  3., nan])

' no_of_children '

array([ 0.,  3.,  2.,  1., nan])

(None, None)

In [9]:
for i in null:
    print("data['"+i+"'].fillna(data['"+i+"'].mode().max(),inplace=True)")

data['h1n1_worry'].fillna(data['h1n1_worry'].mode().max(),inplace=True)
data['h1n1_awareness'].fillna(data['h1n1_awareness'].mode().max(),inplace=True)
data['antiviral_medication'].fillna(data['antiviral_medication'].mode().max(),inplace=True)
data['contact_avoidance'].fillna(data['contact_avoidance'].mode().max(),inplace=True)
data['bought_face_mask'].fillna(data['bought_face_mask'].mode().max(),inplace=True)
data['wash_hands_frequently'].fillna(data['wash_hands_frequently'].mode().max(),inplace=True)
data['avoid_large_gatherings'].fillna(data['avoid_large_gatherings'].mode().max(),inplace=True)
data['reduced_outside_home_cont'].fillna(data['reduced_outside_home_cont'].mode().max(),inplace=True)
data['avoid_touch_face'].fillna(data['avoid_touch_face'].mode().max(),inplace=True)
data['dr_recc_h1n1_vacc'].fillna(data['dr_recc_h1n1_vacc'].mode().max(),inplace=True)
data['dr_recc_seasonal_vacc'].fillna(data['dr_recc_seasonal_vacc'].mode().max(),inplace=True)
data['chronic_medic_condition'

In [10]:
data['h1n1_worry'].fillna(data['h1n1_worry'].mode().max(),inplace=True)
data['h1n1_awareness'].fillna(data['h1n1_awareness'].mode().max(),inplace=True)
data['antiviral_medication'].fillna(data['antiviral_medication'].mode().max(),inplace=True)
data['contact_avoidance'].fillna(data['contact_avoidance'].mode().max(),inplace=True)
data['bought_face_mask'].fillna(data['bought_face_mask'].mode().max(),inplace=True)
data['wash_hands_frequently'].fillna(data['wash_hands_frequently'].mode().max(),inplace=True)
data['avoid_large_gatherings'].fillna(data['avoid_large_gatherings'].mode().max(),inplace=True)
data['reduced_outside_home_cont'].fillna(data['reduced_outside_home_cont'].mode().max(),inplace=True)
data['avoid_touch_face'].fillna(data['avoid_touch_face'].mode().max(),inplace=True)
data['dr_recc_h1n1_vacc'].fillna(data['dr_recc_h1n1_vacc'].mode().max(),inplace=True)
data['dr_recc_seasonal_vacc'].fillna(data['dr_recc_seasonal_vacc'].mode().max(),inplace=True)
data['chronic_medic_condition'].fillna(data['chronic_medic_condition'].mode().max(),inplace=True)
data['cont_child_undr_6_mnths'].fillna(data['cont_child_undr_6_mnths'].mode().max(),inplace=True)
data['is_health_worker'].fillna(data['is_health_worker'].mode().max(),inplace=True)
data['is_h1n1_vacc_effective'].fillna(data['is_h1n1_vacc_effective'].mode().max(),inplace=True)
data['is_h1n1_risky'].fillna(data['is_h1n1_risky'].mode().max(),inplace=True)
data['sick_from_h1n1_vacc'].fillna(data['sick_from_h1n1_vacc'].mode().max(),inplace=True)
data['is_seas_vacc_effective'].fillna(data['is_seas_vacc_effective'].mode().max(),inplace=True)
data['is_seas_risky'].fillna(data['is_seas_risky'].mode().max(),inplace=True)
data['sick_from_seas_vacc'].fillna(data['sick_from_seas_vacc'].mode().max(),inplace=True)
data['qualification'].fillna(data['qualification'].mode().max(),inplace=True)
data['income_level'].fillna(data['income_level'].mode().max(),inplace=True)
data['marital_status'].fillna(data['marital_status'].mode().max(),inplace=True)
data['housing_status'].fillna(data['housing_status'].mode().max(),inplace=True)
data['employment'].fillna(data['employment'].mode().max(),inplace=True)
data['no_of_adults'].fillna(data['no_of_adults'].mode().max(),inplace=True)
data['no_of_children'].fillna(data['no_of_children'].mode().max(),inplace=True)

In [11]:
data.isnull().sum()

unique_id                    0
h1n1_worry                   0
h1n1_awareness               0
antiviral_medication         0
contact_avoidance            0
bought_face_mask             0
wash_hands_frequently        0
avoid_large_gatherings       0
reduced_outside_home_cont    0
avoid_touch_face             0
dr_recc_h1n1_vacc            0
dr_recc_seasonal_vacc        0
chronic_medic_condition      0
cont_child_undr_6_mnths      0
is_health_worker             0
is_h1n1_vacc_effective       0
is_h1n1_risky                0
sick_from_h1n1_vacc          0
is_seas_vacc_effective       0
is_seas_risky                0
sick_from_seas_vacc          0
age_bracket                  0
qualification                0
race                         0
sex                          0
income_level                 0
marital_status               0
housing_status               0
employment                   0
census_msa                   0
no_of_adults                 0
no_of_children               0
h1n1_vac

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   unique_id                  26707 non-null  int64  
 1   h1n1_worry                 26707 non-null  float64
 2   h1n1_awareness             26707 non-null  float64
 3   antiviral_medication       26707 non-null  float64
 4   contact_avoidance          26707 non-null  float64
 5   bought_face_mask           26707 non-null  float64
 6   wash_hands_frequently      26707 non-null  float64
 7   avoid_large_gatherings     26707 non-null  float64
 8   reduced_outside_home_cont  26707 non-null  float64
 9   avoid_touch_face           26707 non-null  float64
 10  dr_recc_h1n1_vacc          26707 non-null  float64
 11  dr_recc_seasonal_vacc      26707 non-null  float64
 12  chronic_medic_condition    26707 non-null  float64
 13  cont_child_undr_6_mnths    26707 non-null  flo

In [13]:
num=[]
for k in col:
    if data[k].dtypes != "object":
        num.append(k)
num      

['unique_id',
 'h1n1_worry',
 'h1n1_awareness',
 'antiviral_medication',
 'contact_avoidance',
 'bought_face_mask',
 'wash_hands_frequently',
 'avoid_large_gatherings',
 'reduced_outside_home_cont',
 'avoid_touch_face',
 'dr_recc_h1n1_vacc',
 'dr_recc_seasonal_vacc',
 'chronic_medic_condition',
 'cont_child_undr_6_mnths',
 'is_health_worker',
 'is_h1n1_vacc_effective',
 'is_h1n1_risky',
 'sick_from_h1n1_vacc',
 'is_seas_vacc_effective',
 'is_seas_risky',
 'sick_from_seas_vacc',
 'no_of_adults',
 'no_of_children',
 'h1n1_vaccine']

In [14]:
le=preprocessing.LabelEncoder()

In [15]:
for i in range(0,len(col)):
    if(col[i]!='unique_id',
 'h1n1_worry',
 'h1n1_awareness',
 'antiviral_medication',
 'contact_avoidance',
 'bought_face_mask',
 'wash_hands_frequently',
 'avoid_large_gatherings',
 'reduced_outside_home_cont',
 'avoid_touch_face',
 'dr_recc_h1n1_vacc',
 'dr_recc_seasonal_vacc',
 'chronic_medic_condition',
 'cont_child_undr_6_mnths',
 'is_health_worker',
 'is_h1n1_vacc_effective',
 'is_h1n1_risky',
 'sick_from_h1n1_vacc',
 'is_seas_vacc_effective',
 'is_seas_risky',
 'sick_from_seas_vacc',
 'no_of_adults',
 'no_of_children',
 'h1n1_vaccine'):
        data1 = le.fit(data[col[i]])
        x2 = data1.transform(data[col[i]])
        x2= pd.DataFrame(x2)
        data[col[i]]=x2

In [16]:
data

unique_id  h1n1_worry  h1n1_awareness  antiviral_medication  \
0              0           1               0                     0   
1              1           3               2                     0   
2              2           1               1                     0   
3              3           1               1                     0   
4              4           2               1                     0   
...          ...         ...             ...                   ...   
26702      26702           2               0                     0   
26703      26703           1               2                     0   
26704      26704           2               2                     0   
26705      26705           1               1                     0   
26706      26706           0               0                     0   

       contact_avoidance  bought_face_mask  wash_hands_frequently  \
0                      0                 0                      0   
1                      1                 0                      1   
2                      1                 0                      0   
3                      1                 0                      1   
4                      1                 0                      1   
...                  ...               ...                    ...   
26702                  1                 0                      0   
26703                  1                 0                      1   
26704                  1                 1                      1   
26705                  0                 0                      0   
26706                  1                 0                      0   

       avoid_large_gatherings  reduced_outside_home_cont  avoid_touch_face  \
0                           0                          1                 1   
1                           0                          1                 1   
2                           0                          0                 0   
3                           1                          0                 0   
4                           1                          0                 1   
...                       ...                        ...               ...   
26702                       0                          1                 0   
26703                       0                          0                 0   
26704                       1                          0                 1   
26705                       0                          0                 1   
26706                       0                          0                 0   

       ...  race  sex  income_level  marital_status  housing_status  \
0      ...     3    0             2               1               0   
1      ...     3    1             2               1               1   
2      ...     3    1             0               1               0   
3      ...     3    0             2               1               1   
4      ...     3    0             0               0               0   
...    ...   ...  ...           ...             ...             ...   
26702  ...     3    0             0               1               0   
26703  ...     3    1             0               1               1   
26704  ...     3    0             0               1               0   
26705  ...     1    0             0               0               1   
26706  ...     3    1             0               0               0   

       employment  census_msa  no_of_adults  no_of_children  h1n1_vaccine  
0               1           2             0               0             0  
1               0           0             0               0             0  
2               0           0             2               0             0  
3               1           1             0               0             0  
4               0           0             1               0             0  
...           ...         ...           ...             ...           ...  
26702          

In [17]:
y=data.h1n1_vaccine
y

0        0
1        0
2        0
3        0
4        0
        ..
26702    0
26703    0
26704    0
26705    0
26706    0
Name: h1n1_vaccine, Length: 26707, dtype: int64

In [18]:
x=data.drop(["h1n1_vaccine"],axis=1)
x

unique_id  h1n1_worry  h1n1_awareness  antiviral_medication  \
0              0           1               0                     0   
1              1           3               2                     0   
2              2           1               1                     0   
3              3           1               1                     0   
4              4           2               1                     0   
...          ...         ...             ...                   ...   
26702      26702           2               0                     0   
26703      26703           1               2                     0   
26704      26704           2               2                     0   
26705      26705           1               1                     0   
26706      26706           0               0                     0   

       contact_avoidance  bought_face_mask  wash_hands_frequently  \
0                      0                 0                      0   
1                      1                 0                      1   
2                      1                 0                      0   
3                      1                 0                      1   
4                      1                 0                      1   
...                  ...               ...                    ...   
26702                  1                 0                      0   
26703                  1                 0                      1   
26704                  1                 1                      1   
26705                  0                 0                      0   
26706                  1                 0                      0   

       avoid_large_gatherings  reduced_outside_home_cont  avoid_touch_face  \
0                           0                          1                 1   
1                           0                          1                 1   
2                           0                          0                 0   
3                           1                          0                 0   
4                           1                          0                 1   
...                       ...                        ...               ...   
26702                       0                          1                 0   
26703                       0                          0                 0   
26704                       1                          0                 1   
26705                       0                          0                 1   
26706                       0                          0                 0   

       ...  qualification  race  sex  income_level  marital_status  \
0      ...              1     3    0             2               1   
1      ...              0     3    1             2               1   
2      ...              2     3    1             0               1   
3      ...              0     3    0             2               1   
4      ...              3     3    0             0               0   
...    ...            ...   ...  ...           ...             ...   
26702  ...              3     3    0             0               1   
26703  ...              2     3    1             0               1   
26704  ...              3     3    0             0               1   
26705  ...              3     1    0             0               0   
26706  ...              3     3    1             0               0   

       housing_status  employment  census_msa  no_of_adults  no_of_children  
0                   0           1           2             0               0  
1                   1           0           0             0               0  
2                   0           0           0             2               0  
3                   1           1           1             0               0  
4                   0           0           0             1               0  
...               ...         ...         ...           ...             ...  
26702        

In [19]:
trainx,testx,trainy,testy = train_test_split(x,y,test_size = 0.2)

  # H1F1 flue predicted using LogisticRegression

In [23]:
logisreg=LogisticRegression().fit(trainx,trainy)
pred=logisreg.predict(testx)
logisrms=sqrt(mean_squared_error(testy,logisreg.predict(testx),squared=False))
pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [21]:
print("Logistic Regression       = ",logisreg.score(testx,testy))
print("Logistic Regression rms   = ",logisrms)

Logistic Regression       =  0.8174840883564208
Logistic Regression rms   =  0.6536197748157196


# score for prediction

In [22]:
from sklearn.metrics import accuracy_score
pred=logisreg.predict(testx)
accuracy_score(testy,pred)

0.8174840883564208