In [1]:
import pandas as pd
import numpy as np
from math import sqrt
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
import xgboost as xg
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler as mms
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error,confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor 
from sklearn.datasets import make_classification
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier,RandomForestClassifier,BaggingClassifier
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor,RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import warnings
warnings.simplefilter("ignore")

In [2]:
data=pd.read_csv(r"C:\Users\sudarson.SUDARSON\Desktop\Imarticus\8 Random Forest\TaxiFarePrediction (1)\Taxi Fare Prediction\Dataset\TaxiFare.csv")
data

unique_id  amount      date_time_of_pickup  longitude_of_pickup  \
0       26:21.0     4.5  2009-06-15 17:26:21 UTC           -73.844311   
1       52:16.0    16.9  2010-01-05 16:52:16 UTC           -74.016048   
2       35:00.0     5.7  2011-08-18 00:35:00 UTC           -73.982738   
3       30:42.0     7.7  2012-04-21 04:30:42 UTC           -73.987130   
4       51:00.0     5.3  2010-03-09 07:51:00 UTC           -73.968095   
...         ...     ...                      ...                  ...   
49995   25:15.0    15.0  2013-06-12 23:25:15 UTC           -73.999973   
49996   19:18.0     7.5  2015-06-22 17:19:18 UTC           -73.984756   
49997   53:00.0     6.9  2011-01-30 04:53:00 UTC           -74.002698   
49998   09:00.0     4.5  2012-11-06 07:09:00 UTC           -73.946062   
49999   13:14.0    10.9  2010-01-13 08:13:14 UTC           -73.932603   

       latitude_of_pickup  longitude_of_dropoff  latitude_of_dropoff  \
0               40.721319            -73.841610            40.712278   
1               40.711303            -73.979268            40.782004   
2               40.761270            -73.991242            40.750562   
3               40.733143            -73.991567            40.758092   
4               40.768008            -73.956655            40.783762   
...                   ...                   ...                  ...   
49995           40.748531            -74.016899            40.705993   
49996           40.768211            -73.987366            40.760597   
49997           40.739428            -73.998108            40.759483   
49998           40.777567            -73.953450            40.779687   
49999           40.763805            -73.932603            40.763805   

       no_of_passenger  
0                    1  
1                    1  
2                    2  
3                    1  
4                    1  
...                ...  
49995                1  
49996                1  
49997                1  
49998                2  
49999                1  

[50000 rows x 8 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   unique_id             50000 non-null  object 
 1   amount                50000 non-null  float64
 2   date_time_of_pickup   50000 non-null  object 
 3   longitude_of_pickup   50000 non-null  float64
 4   latitude_of_pickup    50000 non-null  float64
 5   longitude_of_dropoff  50000 non-null  float64
 6   latitude_of_dropoff   50000 non-null  float64
 7   no_of_passenger       50000 non-null  int64  
dtypes: float64(5), int64(1), object(2)
memory usage: 3.1+ MB


In [4]:
col=data.columns
col

Index(['unique_id', 'amount', 'date_time_of_pickup', 'longitude_of_pickup',
       'latitude_of_pickup', 'longitude_of_dropoff', 'latitude_of_dropoff',
       'no_of_passenger'],
      dtype='object')

In [5]:
for j in col:
    print("display('",j,"')"," ,display(data['"+j+"'].unique())")

display(' unique_id ')  ,display(data['unique_id'].unique())
display(' amount ')  ,display(data['amount'].unique())
display(' date_time_of_pickup ')  ,display(data['date_time_of_pickup'].unique())
display(' longitude_of_pickup ')  ,display(data['longitude_of_pickup'].unique())
display(' latitude_of_pickup ')  ,display(data['latitude_of_pickup'].unique())
display(' longitude_of_dropoff ')  ,display(data['longitude_of_dropoff'].unique())
display(' latitude_of_dropoff ')  ,display(data['latitude_of_dropoff'].unique())
display(' no_of_passenger ')  ,display(data['no_of_passenger'].unique())


In [6]:
display(' unique_id ')  ,display(data['unique_id'].unique())
display(' amount ')  ,display(data['amount'].unique())
display(' date_time_of_pickup ')  ,display(data['date_time_of_pickup'].unique())
display(' longitude_of_pickup ')  ,display(data['longitude_of_pickup'].unique())
display(' latitude_of_pickup ')  ,display(data['latitude_of_pickup'].unique())
display(' longitude_of_dropoff ')  ,display(data['longitude_of_dropoff'].unique())
display(' latitude_of_dropoff ')  ,display(data['latitude_of_dropoff'].unique())
display(' no_of_passenger ')  ,display(data['no_of_passenger'].unique())

' unique_id '

array(['26:21.0', '52:16.0', '35:00.0', ..., '38:13.0', '04:12.0',
       '53:22.0'], dtype=object)

' amount '

array([ 4.5000e+00,  1.6900e+01,  5.7000e+00,  7.7000e+00,  5.3000e+00,
        1.2100e+01,  7.5000e+00,  1.6500e+01,  9.0000e+00,  8.9000e+00,
        5.5000e+00,  4.1000e+00,  7.0000e+00,  5.0000e+00,  1.2500e+01,
        4.0000e+00,  1.0500e+01,  1.1500e+01,  4.9000e+00,  6.1000e+00,
        7.3000e+00,  6.5000e+00,  9.3000e+00,  2.2540e+01,  3.1900e+01,
        1.8100e+01,  5.8000e+01,  9.8000e+00,  8.1000e+00,  1.0900e+01,
        1.7500e+01,  6.9000e+00,  3.3000e+00,  9.7000e+00,  8.0000e+00,
        2.5500e+01,  1.5300e+01,  3.4670e+01,  1.3700e+01,  8.5000e+00,
        3.7000e+00,  1.0100e+01,  1.5070e+01,  2.4900e+01,  1.7000e+01,
        1.2000e+01,  1.1000e+01,  1.3500e+01,  1.4000e+01,  1.0000e+01,
        1.4100e+01,  5.2000e+01,  1.1300e+01,  1.2900e+01,  9.5000e+00,
        3.5000e+01,  1.4500e+01,  3.2500e+01,  1.7700e+01,  1.9000e+01,
        4.9570e+01,  2.2500e+01,  5.2500e+01,  1.6000e+01,  1.7300e+01,
        2.1500e+01,  1.4900e+01,  3.5500e+01,  1.1700e+01,  2.30

' date_time_of_pickup '

array(['2009-06-15 17:26:21 UTC', '2010-01-05 16:52:16 UTC',
       '2011-08-18 00:35:00 UTC', ..., '2011-01-30 04:53:00 UTC',
       '2012-11-06 07:09:00 UTC', '2010-01-13 08:13:14 UTC'], dtype=object)

' longitude_of_pickup '

array([-73.844311, -74.016048, -73.982738, ..., -73.998573, -73.946062,
       -73.932603])

' latitude_of_pickup '

array([40.721319, 40.711303, 40.76127 , ..., 40.719868, 40.739494,
       40.768434])

' longitude_of_dropoff '

array([-73.84161   , -73.979268  , -73.991242  , ..., -74.016899  ,
       -73.98736572, -73.932603  ])

' latitude_of_dropoff '

array([40.712278  , 40.782004  , 40.750562  , ..., 40.705993  ,
       40.76059723, 40.763805  ])

' no_of_passenger '

array([1, 2, 3, 6, 5, 4, 0], dtype=int64)

(None, None)

In [7]:
data["date_time_of_pickup"]=pd.to_datetime(data["date_time_of_pickup"])

In [8]:
x=data.iloc[0:,3:]
x

longitude_of_pickup  latitude_of_pickup  longitude_of_dropoff  \
0               -73.844311           40.721319            -73.841610   
1               -74.016048           40.711303            -73.979268   
2               -73.982738           40.761270            -73.991242   
3               -73.987130           40.733143            -73.991567   
4               -73.968095           40.768008            -73.956655   
...                    ...                 ...                   ...   
49995           -73.999973           40.748531            -74.016899   
49996           -73.984756           40.768211            -73.987366   
49997           -74.002698           40.739428            -73.998108   
49998           -73.946062           40.777567            -73.953450   
49999           -73.932603           40.763805            -73.932603   

       latitude_of_dropoff  no_of_passenger  
0                40.712278                1  
1                40.782004                1  
2                40.750562                2  
3                40.758092                1  
4                40.783762                1  
...                    ...              ...  
49995            40.705993                1  
49996            40.760597                1  
49997            40.759483                1  
49998            40.779687                2  
49999            40.763805                1  

[50000 rows x 5 columns]

In [9]:
y=data["amount"]
y

0         4.5
1        16.9
2         5.7
3         7.7
4         5.3
         ... 
49995    15.0
49996     7.5
49997     6.9
49998     4.5
49999    10.9
Name: amount, Length: 50000, dtype: float64

In [10]:
trainx,testx,trainy,testy = train_test_split(x,y,test_size = 0.2)

In [11]:
randomreg= RandomForestRegressor(max_depth=50, random_state=50).fit(trainx,trainy)
randomreg.predict(testx)
randomrms=sqrt(mean_squared_error(testy,randomreg.predict(testx),squared=False))

# Taxi Fare Price Prediction Predicted

In [12]:
print("RandomForestRegressor       = ",randomreg.score(testx,testy))
print("RandomForestRegressor rms   = ",randomrms)

RandomForestRegressor       =  0.7466701867765195
RandomForestRegressor rms   =  2.2024228667992602


In [14]:
'''param_grid = {
'n_estimators': [100, 80, 60, 55, 51, 45],  
'max_depth': [7, 8],
'random_state':[1,2,3,4,5]
}
# Grid Search CV implementation
randomreg= RandomForestRegressor()
grid_cv = GridSearchCV(randomreg, param_grid ,cv=3)
grid_cv.fit(x,y)
# Return set of parameters with the best performance
display(grid_cv.best_params_)
# Return the performance metric score
display(grid_cv.best_score_)'''

"param_grid = {\n'n_estimators': [100, 80, 60, 55, 51, 45],  \n'max_depth': [7, 8],\n'random_state':[1,2,3,4,5]\n}\n# Grid Search CV implementation\nrandomreg= RandomForestRegressor()\ngrid_cv = GridSearchCV(randomreg, param_grid ,cv=3)\ngrid_cv.fit(x,y)\n# Return set of parameters with the best performance\ndisplay(grid_cv.best_params_)\n# Return the performance metric score\ndisplay(grid_cv.best_score_)"

In [15]:
#randomreg= RandomForestRegressor()

In [19]:
'''param_grid = {
"max_depth": [3, 4, 7, 10, 25],
"gamma": [0.5, 1, 5, 10, 25],
"min_child_weight": [1, 3, 5, 10, 25],
"reg_lambda": [5, 10, 50, 100, 300],
"scale_pos_weight": [1, 3, 5, 10, 25]
}
# Grid Search CV implementation
xgb_cl = xgb.XGBClassifier(objective="binary:logistic")
grid_cv = GridSearchCV(xgb_cl, param_grid, scoring="roc_auc", n_jobs=-1, cv=3)
grid_cv.fit(X_train, y_train)
# Return set of parameters with the best performance
grid_cv.best_params_
# Return the performance metric score
grid_cv.best_score_'''

'param_grid = {\n"max_depth": [3, 4, 7, 10, 25],\n"gamma": [0.5, 1, 5, 10, 25],\n"min_child_weight": [1, 3, 5, 10, 25],\n"reg_lambda": [5, 10, 50, 100, 300],\n"scale_pos_weight": [1, 3, 5, 10, 25]\n}\n# Grid Search CV implementation\nxgb_cl = xgb.XGBClassifier(objective="binary:logistic")\ngrid_cv = GridSearchCV(xgb_cl, param_grid, scoring="roc_auc", n_jobs=-1, cv=3)\ngrid_cv.fit(X_train, y_train)\n# Return set of parameters with the best performance\ngrid_cv.best_params_\n# Return the performance metric score\ngrid_cv.best_score_'

In [20]:
'''#Instantiate SimpleImputer 
si=SimpleImputer(missing_values = np.nan, strategy="median")
si.fit(df[[’age’, 'bmi’]])
  
#Filling missing data with median
df[[’age’, 'bmi’]] = si.transform(df[[’age’, 'bmi’]])'''

'#Instantiate SimpleImputer \nsi=SimpleImputer(missing_values = np.nan, strategy="median")\nsi.fit(df[[’age’, \'bmi’]])\n  \n#Filling missing data with median\ndf[[’age’, \'bmi’]] = si.transform(df[[’age’, \'bmi’]])'