In [2]:
import pandas as pd
import numpy as np
from math import sqrt
from scipy import stats 
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import statsmodels.api as sm 
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler as mms
from sklearn import datasets,linear_model,metrics
from sklearn.metrics import mean_squared_error,confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor 
from sklearn.datasets import make_classification
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier,RandomForestClassifier
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor,RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.model_selection import KFold,cross_val_score

In [3]:
data=pd.read_csv(r"C:\Users\sudarson.SUDARSON\Downloads\TaxiFarePrediction\Taxi Fare Prediction\Dataset\TaxiFare.csv")
data.head()

unique_id  amount      date_time_of_pickup  longitude_of_pickup  \
0   26:21.0     4.5  2009-06-15 17:26:21 UTC           -73.844311   
1   52:16.0    16.9  2010-01-05 16:52:16 UTC           -74.016048   
2   35:00.0     5.7  2011-08-18 00:35:00 UTC           -73.982738   
3   30:42.0     7.7  2012-04-21 04:30:42 UTC           -73.987130   
4   51:00.0     5.3  2010-03-09 07:51:00 UTC           -73.968095   

   latitude_of_pickup  longitude_of_dropoff  latitude_of_dropoff  \
0           40.721319            -73.841610            40.712278   
1           40.711303            -73.979268            40.782004   
2           40.761270            -73.991242            40.750562   
3           40.733143            -73.991567            40.758092   
4           40.768008            -73.956655            40.783762   

   no_of_passenger  
0                1  
1                1  
2                2  
3                1  
4                1

In [4]:
data.isnull().sum()

unique_id               0
amount                  0
date_time_of_pickup     0
longitude_of_pickup     0
latitude_of_pickup      0
longitude_of_dropoff    0
latitude_of_dropoff     0
no_of_passenger         0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   unique_id             50000 non-null  object 
 1   amount                50000 non-null  float64
 2   date_time_of_pickup   50000 non-null  object 
 3   longitude_of_pickup   50000 non-null  float64
 4   latitude_of_pickup    50000 non-null  float64
 5   longitude_of_dropoff  50000 non-null  float64
 6   latitude_of_dropoff   50000 non-null  float64
 7   no_of_passenger       50000 non-null  int64  
dtypes: float64(5), int64(1), object(2)
memory usage: 3.1+ MB


In [6]:
data.unique_id.unique()

array(['26:21.0', '52:16.0', '35:00.0', ..., '38:13.0', '04:12.0',
       '53:22.0'], dtype=object)

In [7]:
data.describe()

amount  longitude_of_pickup  latitude_of_pickup  \
count  50000.000000         50000.000000        50000.000000   
mean      11.364171           -72.509756           39.933759   
std        9.685557            10.393860            6.224857   
min       -5.000000           -75.423848          -74.006893   
25%        6.000000           -73.992062           40.734880   
50%        8.500000           -73.981840           40.752678   
75%       12.500000           -73.967148           40.767360   
max      200.000000            40.783472          401.083332   

       longitude_of_dropoff  latitude_of_dropoff  no_of_passenger  
count          50000.000000         50000.000000     50000.000000  
mean             -72.504616            39.926251         1.667840  
std               10.407570             6.014737         1.289195  
min              -84.654241           -74.006377         0.000000  
25%              -73.991152            40.734372         1.000000  
50%              -73.980082            40.753372         1.000000  
75%              -73.963584            40.768167         2.000000  
max               40.851027            43.415190         6.000000

In [8]:
x=data.iloc[0:,3:]
y=data.amount

In [9]:
dummy = pd.get_dummies(x)
scaler=mms().fit(dummy)
TS = scaler.transform(dummy)
df1= pd.DataFrame(TS)
dummy

longitude_of_pickup  latitude_of_pickup  longitude_of_dropoff  \
0               -73.844311           40.721319            -73.841610   
1               -74.016048           40.711303            -73.979268   
2               -73.982738           40.761270            -73.991242   
3               -73.987130           40.733143            -73.991567   
4               -73.968095           40.768008            -73.956655   
...                    ...                 ...                   ...   
49995           -73.999973           40.748531            -74.016899   
49996           -73.984756           40.768211            -73.987366   
49997           -74.002698           40.739428            -73.998108   
49998           -73.946062           40.777567            -73.953450   
49999           -73.932603           40.763805            -73.932603   

       latitude_of_dropoff  no_of_passenger  
0                40.712278                1  
1                40.782004                1  
2                40.750562                2  
3                40.758092                1  
4                40.783762                1  
...                    ...              ...  
49995            40.705993                1  
49996            40.760597                1  
49997            40.759483                1  
49998            40.779687                2  
49999            40.763805                1  

[50000 rows x 5 columns]

In [10]:
trainx,testx,trainy,testy = train_test_split(df1,y,test_size = 0.2)


In [14]:
linearreg= LinearRegression().fit(trainx,trainy)
linearreg.predict(testx)

array([11.56296153, 12.35321257, 11.23387644, ..., 11.56246943,
       11.23478797, 11.23042196])

In [15]:
linearrms=sqrt(mean_squared_error(testy,linearreg.predict(testx),squared=False))
linearrms

3.152595658156838

In [16]:
decisionreg = DecisionTreeRegressor(random_state=0).fit(trainx,trainy)
decisionreg.predict(testx)

array([ 5.7       , 12.06729167,  7.7       , ...,  6.9       ,
       12.        , 10.9       ])

In [17]:
decisionrms=sqrt(mean_squared_error(testy,decisionreg.predict(testx),squared=False))
decisionrms

2.5966414129297974

In [18]:
randomreg= RandomForestRegressor(max_depth=10, random_state=0).fit(trainx,trainy)
randomreg.predict(testx)

array([ 8.37370038, 11.9988458 ,  8.37370038, ...,  8.37370038,
        8.37370038,  8.71750152])

In [19]:
randomrms=sqrt(mean_squared_error(testy,randomreg.predict(testx),squared=False))
randomrms


2.428512060965517

In [20]:
adabreg = AdaBoostRegressor(random_state=0, n_estimators=100).fit(trainx,trainy)
adabreg.predict(testx)

array([15.62284184, 35.15994104, 15.62284184, ..., 15.62284184,
       15.62284184, 15.62284184])

In [21]:
adabrms=sqrt(mean_squared_error(testy,adabreg.predict(testx),squared=False))
adabrms

3.3005710027223896

In [22]:
gradreg= GradientBoostingRegressor(random_state=0).fit(trainx,trainy)
gradreg.predict(testx)

array([ 8.22904819, 11.67157998,  8.10885573, ...,  8.10885573,
       11.04232318,  8.99776761])

In [23]:
gradrms=sqrt(mean_squared_error(testy,gradreg.predict(testx),squared=False))
gradrms

2.4193931514019567

In [24]:
print("LinearRegression          = ",linearreg.score(testx,testy))
print("Decision Tree Regressor   = ",decisionreg.score(testx,testy))
print("RandomForestRegressor     = ",randomreg.score(testx,testy))
print("AdaBoostRegressor         = ",adabreg.score(testx,testy))
print("GradientBoostingRegressor = ",gradreg.score(testx,testy))

LinearRegression          =  -0.000996291863212928
Decision Tree Regressor   =  0.5393115828229116
RandomForestRegressor     =  0.6475313987515554
AdaBoostRegressor         =  -0.20258475938658838
GradientBoostingRegressor =  0.6527956448655521


In [25]:
rms =[
     ["LinearRegression           rms",linearrms],
     ["decision_tree_regressor    rms",decisionrms],
     ["random_forest_regression   rms",randomrms],
     ["ada_boosting_regression    rms",adabrms],
     ["gradient_boosting_regressionrms",gradrms],
     ]
rms

[['LinearRegression           rms', 3.152595658156838],
 ['decision_tree_regressor    rms', 2.5966414129297974],
 ['random_forest_regression   rms', 2.428512060965517],
 ['ada_boosting_regression    rms', 3.3005710027223896],
 ['gradient_boosting_regressionrms', 2.4193931514019567]]

In [26]:
k=KFold(n_splits=10).get_n_splits(trainx,testx)

In [27]:
cross_val_score(randomreg,testx,testy,cv=k)

array([0.66671468, 0.70540129, 0.6866874 , 0.64168201, 0.53126818,
       0.68156388, 0.49202191, 0.67624941, 0.63040217, 0.7065651 ])